version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: user_registration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7015947615
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 7015947615
      DATABASE_NAME: user_registration
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "3000:3000"

volumes:
  postgres-data:
